[package]
name = "nessie"
version = "0.1.0"
edition = "2021"

[dependencies]
prost = "0.10"
#wasm-bindgen = "0.2.74"
hex = "0.4"
hashbrown = "0.12"

#[lib]
#crate-type = ["cdylib"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html