[package]
name = "kala-context"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
hashbrown = "0.12"
kala-ast = { version = "0.1.0", path = "../kala-ast" }