[package]
name = "jessie-parser"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
jessie-ast = { version = "0.1.0", path = "../jessie-ast" }
utils = { version = "0.1.0", path = "../utils" }