[package]
name = "kala-interpreter"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
jessie-ast = { path = "../jessie-ast" }
utils = { path = "../utils" }
kala-repr = { path = "../kala-repr" }
