[package]
name = "kala-ast"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
swc_ecma_parser = { version = "0.122.12" }
swc_common = { version = "0.29.8" }
swc_ecma_ast   = { version = "0.94.11" }