[package]
name = "kala-parser"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
swc_ecma_ast    = { version = "0.90.15" }
swc_ecma_parser = { version = "0.118.5" }